name: Auto Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const message = `👋 Thanks for opening an issue! \n \n 📌 Please make sure you: \n - Selected the correct **week** label\n - Provided clear details & steps tried\n - Checked **closed issues** to see if your problem was already solved\n \nOur support team will respond soon 🚀`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: message
            });
